name: Generate Documentation from ASCIIDoc

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Build ASCIIDoc with Gradle
        run: ./gradlew clean asciidoctor
